repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix, --indent, "  "]
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        additional_dependencies: ['gibberish-detector']
  # - repo: https://github.com/bridgecrewio/checkov
  #   rev: '2.5.8'
  #   hooks:
  #     - id: checkov
  #       files: \.tf$
  #       args: ["--quiet"] # Add any additional arguments you may want
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.83.5
  #   hooks:
  #     - id: infracost_breakdown
  #       args:
  #         - --args=--path=terraform/
  #       verbose: true
  #     - id: terraform_tflint
  #       #     - id: terraform_tfsec
  #     - id: terraform_fmt
  #     - id: terraform_validate
  #     - id: terraform_docs
  #       args:
  #         - --hook-config=--add-to-existing-file=true
  #         - --hook-config=--create-file-if-not-exist=true
  # - repo: https://github.com/ansible-community/ansible-lint.git
  #   rev: v6.20.3
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       entry: ansible-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--py310-plus]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203']
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        exclude: ^\.secrets\.baseline$
